import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service",
    description: "Generated by create next app",
};

export default function TermLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return <section>{children}</section>
}